### ISSUE TITLE
Linux mint 18 无法配置isatap

### ISSUE THREAD

**Issue by CharlesShang** [tuna/ipv6.tsinghua.edu.cn#16]
Hi，
在Linux mint 17上面直接apt-get安装isatapd然后重启一下网络链接就可以连接ipv6资源了。
升级了linux mint18（ubuntu 16.04）配置isatap就失败了。然后试了 isatap.md 中的方法，也不行。
请教～

**Comment by CharlesShang** [comment]
btw, isatap.md 中那句获得本地ipv4地址貌似有点问题，我使用的是一个比较愚蠢的方法：

   IPV4=`ifconfig -a|grep inet|grep -v 127.0.0.1|grep -v inet6|awk '{print $2}'|tr -d "{地址,addr}:" |grep -v 192|grep -v 10`

最后脚本为：

#!/bin/bash
REMOTE_IP6="2402:f000:1:1501:200:5efe"
REMOTE_IP4="166.111.21.1"
IFACE4=`ip route show|grep default|awk '{print $5}'|grep -v wlx`
IP4=`ifconfig -a|grep inet|grep -v 127.0.0.1|grep -v inet6|awk '{print $2}'|tr -d "{地址,addr}:" |grep -v 192|grep -v 10`
sudo ip tunnel del sit1  # 删除已经创建的设备，若没有则忽略
sudo ip tunnel add sit1 mode sit remote $REMOTE_IP4 local $IP4
sudo ip link set dev sit1 up
sudo ip -6 addr add $REMOTE_IP6:$IP4/64 dev sit1
sudo ip -6 route add default via $REMOTE_IP6:$REMOTE_IP4 dev sit1

**Comment by huiyiqun** [comment]
现在是什么状况？

能创建 tunnel 吗？创建之后可以 ping 通网关吗？

**Comment by CharlesShang** [comment]
@huiyiqun 可以的ping通166.111.21.1的

运行 ifconfig 结果：
eno1      Link encap:Ethernet  HWaddr 10:60:4b:7e:ce:c2  
          inet addr:166.111.139.170  Bcast:166.111.139.255  Mask:255.255.255.0
          inet6 addr: fe80::1260:4bff:fe7e:cec2/64 Scope:Link
          inet6 addr: 2001:da8:200:9009:1260:4bff:fe7e:cec2/64 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:422806 errors:0 dropped:0 overruns:0 frame:0
          TX packets:215393 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:228857863 (228.8 MB)  TX bytes:61367408 (61.3 MB)
          Interrupt:20 Memory:ef400000-ef420000 

enp1s0    Link encap:Ethernet  HWaddr 10:60:4b:7e:ce:c1  
          inet addr:192.168.88.88  Bcast:192.168.255.255  Mask:255.255.0.0
          inet6 addr: fe80::1260:4bff:fe7e:cec1/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:13331 errors:0 dropped:0 overruns:0 frame:0
          TX packets:13626 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:5477411 (5.4 MB)  TX bytes:1503301 (1.5 MB)
          Interrupt:17 Memory:ef300000-ef320000 

is0       Link encap:IPv6-in-IPv4  
          inet6 addr: fe80::200:5efe:a66f:8baa/64 Scope:Link
          inet6 addr: 2402:f000:1:1501:200:5efe:a66f:8baa/64 Scope:Global
          inet6 addr: 2402:f000:1:1501:780b:d16a:149c:1d1c/64 Scope:Global
          inet6 addr: 2402:f000:1:1501::/64 Scope:Global
          UP RUNNING NOARP  MTU:1280  Metric:1
          RX packets:3 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1475 errors:88 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:288 (288.0 B)  TX bytes:122826 (122.8 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:133251 errors:0 dropped:0 overruns:0 frame:0
          TX packets:133251 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:41318536 (41.3 MB)  TX bytes:41318536 (41.3 MB)

sit1      Link encap:IPv6-in-IPv4  
          inet6 addr: fe80::a66f:8baa/64 Scope:Link
          inet6 addr: 2402:f000:1:1501:200:5efe:a66f:8baa/64 Scope:Global
          UP POINTOPOINT RUNNING NOARP  MTU:1480  Metric:1
          RX packets:2 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:192 (192.0 B)  TX bytes:504 (504.0 B)

上面sit1应该是建立的tunnel

**Comment by Blaok** [comment]
@CharlesShang 你怎么有这么多带IPv6地址的interface。。。

`ip -6 route show`一下看一眼默认网关是啥。想强行用ISATAP的话最后一句改成

`sudo ip -6 route add default via $REMOTE_IP6:$REMOTE_IP4 dev sit1 metric 1`

现在大部分有线网应该都是双栈了吧，为啥要用ISATAP？

**Comment by CharlesShang** [comment]
@Blaok 谢谢，Problem solved！ 
但是目前我们实验室（fit）要链接ipv6还只能是isatap。。由于对网络方面了解很浅（只限于搜索并粘帖一下脚本），我也不知道为什么。
附上完整的脚本，希望对同样问题的人有帮助：

```
#!/bin/bash
REMOTE_IP6="2402:f000:1:1501:200:5efe"
REMOTE_IP4="166.111.21.1"
IFACE4=`ip route show|grep default|awk '{print $5}'|grep -v wlx`
IP4=`ifconfig -a|grep inet|grep -v 127.0.0.1|grep -v inet6|awk '{print $2}'|tr -d "{地址,addr}:" |grep -v 192|grep -v 10`
sudo ip tunnel del sit1  # 删除已经创建的设备，若没有则忽略
sudo ip tunnel add sit1 mode sit remote $REMOTE_IP4 local $IP4
sudo ip link set dev sit1 up
sudo ip -6 addr add $REMOTE_IP6:$IP4/64 dev sit1
sudo ip -6 route add default via $REMOTE_IP6:$REMOTE_IP4 dev sit1 metric 1
```

**Comment by CharlesShang** [comment]
I'm closing this issue, thank you!
