### ISSUE TITLE
网站无法访问

### ISSUE THREAD

**Issue by liangffzz** [tuna/ipv6.tsinghua.edu.cn#19]
RT
似乎持续了一段时间了……

C:\WINDOWS\system32>tracert -d ipv6.tsinghua.edu.cn

通过最多 30 个跃点跟踪
到 ipv6.tsinghua.edu.cn [2402:f000:1:9a1::9:164] 的路由:

  1     4 ms     *        *     2402:f000:1:1501:0:5efe:166.111.21.1
  2     2 ms     1 ms     4 ms  2001:da8:200:f001::2
  3     1 ms     2 ms     1 ms  2402:f000:0:244::70
  4     4 ms     2 ms     4 ms  2402:f000:0:3cc::205
  5     *        *        *     请求超时。
  6     *        *     无法访问目标主机。

跟踪完成。

**Comment by shankerwangmiao** [comment]
嗯，是网络中心前一次搬家的遗留问题，正在联系处理

**Comment by gaotongsh** [comment]
现在网站依然无法访问，问题还没有解决吗？ @shankerwangmiao

**Comment by shankerwangmiao** [comment]
已经重新搭建了
