### ISSUE TITLE
ipv6连接国外地址限速严重

### ISSUE THREAD

**Issue by complexly** [tuna/ipv6.tsinghua.edu.cn#24]
2018年3月21日前后，校园网对境外ipv6地址限速严重，校内原生和isatap隧道的ipv6地址基本无法通过v6方式连接在国外的服务器，但同一服务器利用v4地址连接正常，连接国内其他ipv6服务正常。

**Comment by shankerwangmiao** [comment]
不是校园网进行的限制，是 6NOC 那边搞的。

**Comment by liwt31** [comment]
@complexly  亲测使用[kcptun](https://github.com/xtaci/kcptun)可以加速
