### ISSUE TITLE
怎么还原设置啊？

### ISSUE THREAD

**Issue by marsggbo** [tuna/ipv6.tsinghua.edu.cn#27]
设置之后的确能进入教育bt网了，但是谷歌却上不去了。（不在大陆，平时是可以正常访问谷歌的）

**Comment by alick** [comment]
你做了哪些设置？

**Comment by marsggbo** [comment]
我的是windows系统，就是照着你的那两个命令号敲了之后就可以正常访问了，没有做其他的设置。但是谷歌就很难上去。

**Comment by alick** [comment]
ISATAP? 禁用请搜索 "windows disable istap"。Windows 8.1 的话可参考
https://www.wikihow.com/Disable-Isatap-Adapter-in-Windows-8.1

连 Google 慢或者连不上的原因是默认优先 IPv6，而设置了清华 ISATAP 服务后，流量要在清华的服务器周转。

**Comment by alick** [comment]
我怀疑如下命令就可以禁用 isatap，未测试：

    netsh int ipv6 isatap set state disable

**Comment by marsggbo** [comment]
我试过了，`netsh int ipv6 isatap set state disable`命令就可以了。谢谢
