### ISSUE TITLE
连接pulse secure访问不了ipv6

### ISSUE THREAD

**Issue by StephenAnboer** [tuna/ipv6.tsinghua.edu.cn#33]
按照https://ipv6.tsinghua.edu.cn/isatap/ 教程配置了isatap，关闭了原生ipv6，关闭了teredo，关闭了6to4，打开了ip helper不知道为什么还是不能访问ipv6。我的隧道ipv6地址是fe80::开头，不是网站上说的2402:f000:1:1501:，不知道哪里出了问题。

ipconfig关于隧道部分显示如下：

隧道适配器 isatap.tsinghua.edu.cn:

   连接特定的 DNS 后缀 . . . . . . . : tsinghua.edu.cn
   本地链接 IPv6 地址. . . . . . . . : fe80::200:5efe:166.111.236.227%55
   默认网关. . . . . . . . . . . . . :

以太网适配器 以太网 4:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :

隧道适配器 isatap.{16E9916A-159A-42B2-BE99-D5CBD895C637}:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::5efe:192.168.0.107%25
   默认网关. . . . . . . . . . . . . :

**Comment by StephenAnboer** [comment]
刚查到：
如果你确定有 IPv6，但我们检测不到：有两个可能的原因。要么你的单位通过网络策略阻断了与外界的 IPv6 通信，要么你看到的 IPv6 地址不是公网地址。任何以“::”“fc”“fd”或“fe”开头的地址都无法接入 IPv6 互联网。

尴尬了，不知道为什么我配置完得到的地址是fe开头，不是2404开头

**Comment by StephenAnboer** [comment]
ping isatap.tsinghua.edu.cn结果：

正在 Ping isatap.tsinghua.edu.cn [166.111.21.1] 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

166.111.21.1 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

**Comment by eliasyin** [comment]
俺也一样....我用的是无线网，WLAN状态里边IPV6直接是无网络访问权限。。。所以这是运行商的问题吗

**Comment by eliasyin** [comment]
似乎发现了问题，在交大的[ISATAP说明](https://net.sjtu.edu.cn/info/1153/1872.htm)中有这样几句话：

> 使用ISATAP隧道，用户与isatap服务器之间不能经过网络地址转换(NAT)。 
家用级路由器后的用户由于IP地址无法被isatap.sjtu.edu.cn直接访问到，因而一般都无法使用该服务。 该服务仅提供给校内用户使用。
所以校外还是不行的。。。蓝瘦

**Comment by njxxwhx** [comment]
我也连不上，本地链接 IPv6 地址也有fe80前缀，能不能有个信息化技术中心或TUNA协会的人给个回复呢？

**Comment by eliasyin** [comment]
> 我也连不上，本地链接 IPv6 地址也有fe80前缀，能不能有个信息化技术中心或TUNA协会的人给个回复呢？

fe80开头的地址没啥意义，是默认的ipv6地址。只要电脑支持ipv6协议都会有这个地址。校外想访问pt站不太容易，但是似乎有一些办法，你可以参考这个[简书上的教程](https://www.jianshu.com/p/cdfa2323f9ff)，我还没试过，不知道行不行

**Comment by shankerwangmiao** [comment]
经与信息化技术中心咨询得知，由于 sslvpn 服务器被滥用于与 isatap 服务器建立 ipv6 隧道，导致 sslvpn 服务过于拥挤，影响正常回校工作网络接入，因此暂时在 sslvpn 服务器上封禁了 isatap 服务器，即通过 sslvpn 接入校内网络后，暂时不能再连通 isatap 服务器。
