### ISSUE TITLE
[macOS] 如何通过sslvpn+isatap访问ipv6资源

### ISSUE THREAD

**Issue by Yunoinsky** [tuna/ipv6.tsinghua.edu.cn#34]
操作系统：macOS 10.15.3
先通过pulse secure接入校园网，可以正常访问校内资源 😃 
之后使用ipv6.tsinghua.edu.cn上的脚本配置isatap，无法访问ipv6资源 😭 

同一网络环境下，已经在windows 10 平台上试验过相关解决方案，可以访问ipv6资源，大概不是网络环境的问题。
求更新macOS的解决方案

**Comment by StephenAnboer** [comment]
> 操作系统：macOS 10.15.3
> 先通过pulse secure接入校园网，可以正常访问校内资源 😃
> 之后使用ipv6.tsinghua.edu.cn上的脚本配置isatap，无法访问ipv6资源 😭
> 
> 同一网络环境下，已经在windows 10 平台上试验过相关解决方案，可以访问ipv6资源，大概不是网络环境的问题。
> 求更新macOS的解决方案

求问，windows 10 平台是怎么解决的呀？我按照教程配置，分配不到正确的ipv6地址

**Comment by zx1239856** [comment]
> > 操作系统：macOS 10.15.3
> > 先通过pulse secure接入校园网，可以正常访问校内资源 smiley
> > 之后使用ipv6.tsinghua.edu.cn上的脚本配置isatap，无法访问ipv6资源 sob
> > 同一网络环境下，已经在windows 10 平台上试验过相关解决方案，可以访问ipv6资源，大概不是网络环境的问题。
> > 求更新macOS的解决方案
> 
> 求问，windows 10 平台是怎么解决的呀？我按照教程配置，分配不到正确的ipv6地址

在几周前我一直可以使用SSLVPN拿到IPv6地址，这几天突然不行了....猜测ISATAP Server出问题了/增加了访问控制

**Comment by shankerwangmiao** [comment]
ref #33
