### ISSUE TITLE
请问最近隧道是不能用了？

### ISSUE THREAD

**Issue by stefanieren** [tuna/ipv6.tsinghua.edu.cn#37]
从上周配置的隧道就访问不了PT站，ping 166.111.21.1 也没反应了。
是隧道有新的变化还是直接不行了呀？

**Comment by shankerwangmiao** [comment]
据了解，ISATAP 隧道不再对校外提供服务，如果您位于校外，应该不能再成功连接隧道服务。

**Comment by stefanieren** [comment]
多谢回复~~
