### ISSUE TITLE
求助，为啥设置了没有反应呢，通过HE网站配置的隧道可以，清华的不行

### ISSUE THREAD

**Issue by liu191388548** [tuna/ipv6.tsinghua.edu.cn#38]
请问是为什么呢，以前都可以

**Comment by shankerwangmiao** [comment]
具体是设置了什么？进行了什么操作？你希望得到什么结果？实际上的表现是什么？

**Comment by liu191388548** [comment]
> 么操作？你希望得到什么结果？实际上的表现是什么？

sit1: flags=209<UP,POINTOPOINT,RUNNING,NOARP>  mtu 1480
        inet6 fe80::68f3:123d  prefixlen 64  scopeid 0x20<link>
        inet6 2402:f000:1:1501:200:5efe:68f3:123d  prefixlen 64  scopeid 0x0<global>
        sit  txqueuelen 1000  (IPv6-in-IPv4)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 13  bytes 1328 (1.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
有显示v6分配 就是 ping6  不懂谷歌呢
PING google.com(lax28s15-in-x0e.1e100.net (2607:f8b0:4007:804::200e)) 56 data bytes
在这个地方就没有反应了  
用的是搬瓦工  想到北邮人呢
谢谢回复

**Comment by liu191388548** [comment]
[root@clean-path-1 ~]# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 104.243.18.61  netmask 255.255.240.0  broadcast 104.243.31.255
        inet6 fe80::a8aa:ff:fe16:84f9  prefixlen 64  scopeid 0x20<link>
        ether aa:aa:00:16:84:f9  txqueuelen 1000  (Ethernet)
        RX packets 352288  bytes 474832617 (452.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 341829  bytes 485947790 (463.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether ba:aa:00:16:84:f9  txqueuelen 1000  (Ethernet)
        RX packets 161140  bytes 54898028 (52.3 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2531  bytes 432078 (421.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

is_sjtu: flags=209<UP,POINTOPOINT,RUNNING,NOARP>  mtu 1480
        inet6 fe80::200:5efe:68f3:123d  prefixlen 64  scopeid 0x20<link>
        sit  txqueuelen 1000  (IPv6-in-IPv4)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 51099  bytes 4877715 (4.6 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 51099  bytes 4877715 (4.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

sit0: flags=193<UP,RUNNING,NOARP>  mtu 1480
        inet6 ::104.243.18.61  prefixlen 96  scopeid 0x80<compat,global>
        inet6 ::127.0.0.1  prefixlen 96  scopeid 0x90<compat,host>
        sit  txqueuelen 1000  (IPv6-in-IPv4)
        RX packets 29  bytes 3719 (3.6 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

sit1: flags=209<UP,POINTOPOINT,RUNNING,NOARP>  mtu 1480
        inet6 fe80::68f3:123d  prefixlen 64  scopeid 0x20<link>
        inet6 2402:f000:1:1501:200:5efe:68f3:123d  prefixlen 64  scopeid 0x0<global>
        sit  txqueuelen 1000  (IPv6-in-IPv4)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 16  bytes 1664 (1.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by shankerwangmiao** [comment]
您好，清华的 istap 服务近期不对校外开放

**Comment by liu191388548** [comment]
> 务近期不对校外开放

好的收到 谢谢 我就说为啥以前可以 现在不行咯呢
