### ISSUE TITLE
使用知识共享协议

### ISSUE THREAD

**Issue by Blaok** [tuna/ipv6.tsinghua.edu.cn#8]
建议CC BY-SA 4.0，虽然我也不知道那是啥。

**Comment by alick** [comment]
有 4.0 国际版的，原则上各国适用（具体要问律师），有中文翻译。

https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh

**Comment by Blaok** [comment]
😅我觉得有一个就好，话说不同版本到底有什么不一样
